import React, { Component } from "react";
import styled from 'styled-components';


const CenteredItem = styled.div`
    display: flex;
    flex-direction: column;
    align-items: center;
`;

const Loading = styled.div`
@keyframes ldio-xwp8z3h6fe {
  0% { transform: translate(-50%,-50%) rotate(0deg); }
  100% { transform: translate(-50%,-50%) rotate(360deg); }
}
.ldio-xwp8z3h6fe div {
  position: absolute;
  width: 32.400000000000006px;
  height: 32.400000000000006px;
  border: 10.8px solid #141414;
  border-top-color: transparent;
  border-radius: 50%;
}
.ldio-xwp8z3h6fe div {
  animation: ldio-xwp8z3h6fe 1s linear infinite;
  top: 54px;
  left: 54px
}
.loadingio-spinner-rolling-x23n723hri {
  width: 108px;
  height: 108px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-xwp8z3h6fe {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-xwp8z3h6fe div { box-sizing: content-box; }
/* generated by https://loading.io/ */`;

class StartfiLoader extends Component {

    render() {
        return (
            <CenteredItem>
                <Loading>
                    <div className="loadingio-spinner-rolling-x23n723hri"><div className="ldio-xwp8z3h6fe">
                        <div></div>
                    </div></div>
                </Loading>
            </CenteredItem>
        )
    }

}

export default StartfiLoader;