export enum STEP {
  STEP1 = 1,
  STEP2 = 2,
  STEP3 = 3,
  NFT_SUMMARY = 4,
  ALLOW_TRANSFER = 5,
  ADD_NFT = 6,
  CHOOSE_TYPE = 7,
  AUCTION_DETAILS = 8,
  AUCTION_SUMMARY = 9,
  ALLOW_MONETIZING = 10,
  ADD_AUCTION = 11
}
